- name: Install Maven
  ansible.builtin.dnf:
    name: 'maven'
    state: present

- name: Load app pre-reqs
  ansible.builtin.import_tasks: app prereqs.yml

- name: Install maven dependencies
  ansible.builtin.shell: mvn clean package ; mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app/

- name: Load systemd
  ansible.builtin.import_tasks: systemd.yml